#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Sandbox round: prove the Squad rail end-to-end with test keys WITHOUT
# touching live buyers. platform_settings is a single global row shared by
# prod/preview/dev, so the admin toggle stays OFF until the live round.
ENV_FILE=".env.local"

TOTAL_STAGES=5

# Reads the Supabase URL + service key out of ENV_FILE and asks REST whether
# the squad_enabled column exists yet. 200 => migration applied; 400/42703 =>
# not yet. Never prints the key.
_migration_applied() {
  local url key code
  url=$(_existing NEXT_PUBLIC_SUPABASE_URL || true)
  key=$(_existing SUPABASE_SERVICE_ROLE_KEY || true)
  [[ -n "$url" && -n "$key" ]] || return 1
  code=$(curl -sS -o /dev/null -w '%{http_code}' --max-time 15 \
    -H "apikey: $key" \
    -H "Authorization: Bearer $key" \
    "$url/rest/v1/platform_settings?select=squad_enabled" 2>/dev/null) || return 1
  [[ "$code" == "200" ]]
}

_supabase_ref() {
  local url ref
  url=$(_existing NEXT_PUBLIC_SUPABASE_URL || true)
  ref=${url#*://}
  ref=${ref%%.*}
  printf '%s' "$ref"
}

banner "Squad setup · sandbox round"

# ── Stage 1: migration ──────────────────────────────────────────────────────
stage "Database: add squad_enabled"
say "Adds the squad_enabled setting and widens the four gateway CHECK constraints"
say "so rows can be written as gateway='squad'. Squad stays OFF after this."
REF=$(_supabase_ref)
if [[ -n "$REF" ]]; then
  open_url "https://supabase.com/dashboard/project/${REF}/sql/new"
else
  open_url "https://supabase.com/dashboard"
fi
step "In the SQL editor, paste the whole of this file and click Run:"
note "    supabase/migrations/0033_squad_gateway.sql"
step "Then run this to confirm it took (expect one row, squad_enabled = false):"
note "    select squad_enabled from platform_settings;"
for attempt in 1 2 3; do
  if _migration_applied; then
    printf '  %s✓ squad_enabled column is live%s\n' "$GREEN" "$RESET"
    break
  fi
  if [[ "$attempt" == "3" ]]; then
    warn "squad_enabled still missing -- re-run the SQL, then re-run this wizard."
    exit 1
  fi
  warn "squad_enabled not visible yet."
  pause "Press Enter to re-check (or Ctrl-C, paste the SQL, then re-run)"
done

# ── Stage 2: sandbox keys ───────────────────────────────────────────────────
stage "Squad sandbox: API keys"
say "Grab the SANDBOX keys -- the sandbox portal is separate from the live one."
open_url "https://sandbox.squadco.com"
step "Sign up (or sign in) at sandbox.squadco.com -- NOT dashboard.squadco.com."
step "Open the profile menu in the top corner -> Merchant Settings ->"
step "API & Webhooks tab. In sandbox the keys also sit at the bottom of the"
step "Get Started page."
step "Copy the Test Public key (looks like test_pk_... or sandbox_pk_...)."
ask NEXT_PUBLIC_SQUAD_PUBLIC_KEY "Paste the public key:"
step "Copy the Test Secret key (looks like sandbox_sk_...)."
ask_secret SQUAD_SECRET_KEY "Paste the secret key:"

case "$SQUAD_SECRET_KEY" in
  sandbox_sk_*|*sandbox*) ;;
  *)
    warn "that secret does not look like a sandbox key (expected sandbox_sk_...)."
    warn "you may have pasted a LIVE key -- confirm before continuing."
    ;;
esac

write_env NEXT_PUBLIC_SQUAD_PUBLIC_KEY "$NEXT_PUBLIC_SQUAD_PUBLIC_KEY"
write_env SQUAD_SECRET_KEY "$SQUAD_SECRET_KEY"
# Dev-only escape hatch: without it local dev has no geo header (-> Nigeria ->
# Monipay) and squad_enabled is off globally, so the Squad branch is
# unreachable. lib/geo.ts ignores this in production builds.
write_env PREEM_FORCE_GATEWAY "squad"

# ── Stage 3: webhook ────────────────────────────────────────────────────────
stage "Squad sandbox: webhook URL"
say "Backstop for buyers who close the tab before the callback runs."
open_url "https://sandbox.squadco.com"
step "Profile -> API & Webhooks -> Webhook URL field."
step "Paste exactly this and Save:"
note "    https://preem.ng/api/webhooks/squad"
step "Leave the Redirect URL field EMPTY -- our widget never redirects."
warn "Webhook config is PER PORTAL: repeat this on dashboard.squadco.com at go-live."
note "Your local dev server can't receive Squad's webhooks (not public), so during"
note "this round the popup callback is what confirms the payment. That's expected."
pause "Press Enter once the webhook URL is saved"

# ── Stage 4: test payment ───────────────────────────────────────────────────
stage "Test checkout with a sandbox card"
if curl -sf -o /dev/null --max-time 3 http://localhost:3000 2>/dev/null; then
  printf '  %s✓ dev server already running on :3000%s\n' "$GREEN" "$RESET"
else
  step "Start the app in another terminal:  npm run dev"
  for i in $(seq 1 40); do
    if curl -sf -o /dev/null --max-time 3 http://localhost:3000 2>/dev/null; then
      printf '  %s✓ dev server is up%s\n' "$GREEN" "$RESET"
      break
    fi
    if [[ "$i" == "40" ]]; then
      warn "localhost:3000 never came up; re-run this wizard later."
      exit 1
    fi
    sleep 3
  done
fi
note "PREEM_FORCE_GATEWAY=squad is set, so every checkout here picks Squad"
note "regardless of IP or the admin toggle. Nothing in production is affected."
open_url "http://localhost:3000/explore"
step "Open any published drop -> Buy access -> pick a price -> Continue."
step "The popup must be Squad's, not Paystack's."
step "Pay with a sandbox card, e.g. 4242 4242 4242 4242, any future expiry, any CVV."
step "Confirm it lands on 'You're in!' rather than the error screen."
warn "Local dev writes to the production Supabase project -- an abandoned test row"
warn "just sits pending until the nightly expire-pendings cron clears it."
if confirm "Did the sandbox purchase complete?"; then
  printf '  %s✓ sandbox round proven end-to-end%s\n' "$GREEN" "$RESET"
else
  warn "not proven yet -- check /tmp/preem-dev.log and the browser console, then"
  warn "re-run this wizard; stages 1-3 are idempotent and will be skipped over."
fi

# ── Stage 5: go live ────────────────────────────────────────────────────────
stage "Go live with real Squad keys"
say "Still to do before real buyers are routed to Squad (admin toggle is OFF):"
step "Repeat stage 2 against dashboard.squadco.com to get the LIVE keys."
step "Repeat stage 3 on the LIVE portal -- webhook config is per-portal."
step "Put the live keys in Vercel Production:"
note "    vercel env add NEXT_PUBLIC_SQUAD_PUBLIC_KEY production"
note "    vercel env add SQUAD_SECRET_KEY production"
step "Then flip Squad on: https://preem.ng/admin/settings ->"
step "'Squad -- international' ON -> Save. Non-Nigerian buyers now go to Squad."
warn "Never flip the toggle on while SANDBOX keys sit in Production -- live"
warn "buyers would be sent to the sandbox."

if confirm "Set the LIVE keys in Vercel Production now?"; then
  open_url "https://dashboard.squadco.com"
  step "Profile -> API & Webhooks -> copy the Live Public key."
  ask LIVE_PUBLIC_KEY "Paste the live public key:"
  step "Copy the Live Secret key."
  ask_secret LIVE_SECRET_KEY "Paste the live secret key:"
  _vercel_set() {
    local name="$1" env="$2" value="$3"
    if ! command -v vercel >/dev/null 2>&1; then
      SKIPPED+=("Vercel $name ($env): vercel CLI not found")
      warn "vercel CLI not found; set $name for $env by hand"
      return
    fi
    if printf '%s' "$value" | vercel env add "$name" "$env" --force --yes >/dev/null 2>&1; then
      WRITTEN_SECRET+=("Vercel $name ($env)")
      printf '  %s✓ set%s Vercel %s for %s\n' "$GREEN" "$RESET" "$name" "$env"
    else
      SKIPPED+=("Vercel $name ($env)")
      warn "could not set Vercel $name for $env -- run it by hand"
    fi
  }
  _vercel_set NEXT_PUBLIC_SQUAD_PUBLIC_KEY production "$LIVE_PUBLIC_KEY"
  _vercel_set SQUAD_SECRET_KEY production "$LIVE_SECRET_KEY"
  note "Your .env.local keeps the SANDBOX keys, so local dev stays on test."
  note "Flip the toggle on now at https://preem.ng/admin/settings"
else
  note "skipped -- run this stage again when the live keys are ready."
fi

finish
